version: "3"
services:
  odop:
    container_name: odop
    restart: unless-stopped 
    image: odop
    env_file: .env
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mongo
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
        - "127.0.0.1:8443:8443"
    
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo:4.4.1
    env_file: .env
    environment: 
      MONGO_INITDB_ROOT_USERNAME: $ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/createUser.js:/docker-entrypoint-initdb.d/createUser.js:ro # to create manually
      - ./mongo/initDb.js:/docker-entrypoint-initdb.d/initDb.js:ro
